# threeplusone schema
# --- !Downs
delete from countries if exists;

# --- !Ups
# --- Countries
INSERT INTO countries (name,abbreviation) VALUES('', '');
INSERT INTO countries (name,abbreviation) VALUES('Afganistán', 'AFG');
INSERT INTO countries (name,abbreviation) VALUES('Åland', 'ALA');
INSERT INTO countries (name,abbreviation) VALUES('Albania', 'ALB');
INSERT INTO countries (name,abbreviation) VALUES('Alemania', 'DEU');
INSERT INTO countries (name,abbreviation) VALUES('Andorra', 'AND');
INSERT INTO countries (name,abbreviation) VALUES('Angola', 'AGO');
INSERT INTO countries (name,abbreviation) VALUES('Anguila', 'AIA');
INSERT INTO countries (name,abbreviation) VALUES('Antártida', 'ATA');
INSERT INTO countries (name,abbreviation) VALUES('Antigua y Barbuda', 'ATG');
INSERT INTO countries (name,abbreviation) VALUES('Antillas Neerlandesas', 'ANT');
INSERT INTO countries (name,abbreviation) VALUES('Arabia Saudita', 'SAU');
INSERT INTO countries (name,abbreviation) VALUES('Argelia', 'DZA');
INSERT INTO countries (name,abbreviation) VALUES('Argentina', 'ARG');
INSERT INTO countries (name,abbreviation) VALUES('Armenia', 'ARM');
INSERT INTO countries (name,abbreviation) VALUES('Aruba', 'ABW');
INSERT INTO countries (name,abbreviation) VALUES('Australia', 'AUS');
INSERT INTO countries (name,abbreviation) VALUES('Austria', 'AUT');
INSERT INTO countries (name,abbreviation) VALUES('Azerbaiyán', 'AZE');
INSERT INTO countries (name,abbreviation) VALUES('Bahamas', 'BHS');
INSERT INTO countries (name,abbreviation) VALUES('Bahréin', 'BHR');
INSERT INTO countries (name,abbreviation) VALUES('Bangladesh', 'BGD');
INSERT INTO countries (name,abbreviation) VALUES('Barbados', 'BRB');
INSERT INTO countries (name,abbreviation) VALUES('Bielorrusia', 'BLR');
INSERT INTO countries (name,abbreviation) VALUES('Bélgica', 'BEL');
INSERT INTO countries (name,abbreviation) VALUES('Belice', 'BLZ');
INSERT INTO countries (name,abbreviation) VALUES('Benín', 'BEN');
INSERT INTO countries (name,abbreviation) VALUES('Bermudas', 'BMU');
INSERT INTO countries (name,abbreviation) VALUES('Bután', 'BTN');
INSERT INTO countries (name,abbreviation) VALUES('Bolivia', 'BOL');
INSERT INTO countries (name,abbreviation) VALUES('Bosnia y Herzegovina', 'BIH');
INSERT INTO countries (name,abbreviation) VALUES('Botsuana', 'BWA');
INSERT INTO countries (name,abbreviation) VALUES('Isla Bouvet', 'BVT');
INSERT INTO countries (name,abbreviation) VALUES('Brasil', 'BRA');
INSERT INTO countries (name,abbreviation) VALUES('Brunéi', 'BRN');
INSERT INTO countries (name,abbreviation) VALUES('Bulgaria', 'BGR');
INSERT INTO countries (name,abbreviation) VALUES('Burkina Faso', 'BFA');
INSERT INTO countries (name,abbreviation) VALUES('Burundi', 'BDI');
INSERT INTO countries (name,abbreviation) VALUES('Cabo Verde', 'CPV');
INSERT INTO countries (name,abbreviation) VALUES('Islas Caimán', 'CYM');
INSERT INTO countries (name,abbreviation) VALUES('Camboya', 'KHM');
INSERT INTO countries (name,abbreviation) VALUES('Camerún', 'CMR');
INSERT INTO countries (name,abbreviation) VALUES('Canadá', 'CAN');
INSERT INTO countries (name,abbreviation) VALUES('República Centroafricana', 'CAF');
INSERT INTO countries (name,abbreviation) VALUES('Chad', 'TCD');
INSERT INTO countries (name,abbreviation) VALUES('República Checa', 'CZE');
INSERT INTO countries (name,abbreviation) VALUES('Chile', 'CHL');
INSERT INTO countries (name,abbreviation) VALUES('China', 'CHN');
INSERT INTO countries (name,abbreviation) VALUES('Chipre', 'CYP');
INSERT INTO countries (name,abbreviation) VALUES('Islas Cocos', 'CCK');
INSERT INTO countries (name,abbreviation) VALUES('Colombia', 'COL');
INSERT INTO countries (name,abbreviation) VALUES('Comoras', 'COM');
INSERT INTO countries (name,abbreviation) VALUES('República del Congo', 'COG');
INSERT INTO countries (name,abbreviation) VALUES('República Democrática del Congo', 'COD');
INSERT INTO countries (name,abbreviation) VALUES('Islas Cook', 'COK');
INSERT INTO countries (name,abbreviation) VALUES('Corea del Norte', 'PRK');
INSERT INTO countries (name,abbreviation) VALUES('Corea del Sur', 'KOR');
INSERT INTO countries (name,abbreviation) VALUES('Costa de Marfil', 'CIV');
INSERT INTO countries (name,abbreviation) VALUES('Costa Rica', 'CRI');
INSERT INTO countries (name,abbreviation) VALUES('Croacia', 'HRV');
INSERT INTO countries (name,abbreviation) VALUES('Cuba', 'CUB');
INSERT INTO countries (name,abbreviation) VALUES('Dinamarca', 'DNK');
INSERT INTO countries (name,abbreviation) VALUES('Dominica', 'DMA');
INSERT INTO countries (name,abbreviation) VALUES('República Dominicana', 'DOM');
INSERT INTO countries (name,abbreviation) VALUES('Ecuador', 'ECU');
INSERT INTO countries (name,abbreviation) VALUES('Egipto', 'EGY');
INSERT INTO countries (name,abbreviation) VALUES('El Salvador', 'SLV');
INSERT INTO countries (name,abbreviation) VALUES('Emiratos Árabes Unidos', 'ARE');
INSERT INTO countries (name,abbreviation) VALUES('Eritrea', 'ERI');
INSERT INTO countries (name,abbreviation) VALUES('Eslovaquia', 'SVK');
INSERT INTO countries (name,abbreviation) VALUES('Eslovenia', 'SVN');
INSERT INTO countries (name,abbreviation) VALUES('España', 'ESP');
INSERT INTO countries (name,abbreviation) VALUES('España(Ceuta y Melilla)', 'ESP');
INSERT INTO countries (name,abbreviation) VALUES('Estados Unidos', 'USA');
INSERT INTO countries (name,abbreviation) VALUES('Islas ultramarinas de Estados Unidos', 'UMI');
INSERT INTO countries (name,abbreviation) VALUES('Estonia', 'EST');
INSERT INTO countries (name,abbreviation) VALUES('Etiopía', 'ETH');
INSERT INTO countries (name,abbreviation) VALUES('Islas Feroe', 'FRO');
INSERT INTO countries (name,abbreviation) VALUES('Filipinas', 'PHL');
INSERT INTO countries (name,abbreviation) VALUES('Finlandia', 'FIN');
INSERT INTO countries (name,abbreviation) VALUES('Fiyi', 'FJI');
INSERT INTO countries (name,abbreviation) VALUES('Francia', 'FRA');
INSERT INTO countries (name,abbreviation) VALUES('Gabón', 'GAB');
INSERT INTO countries (name,abbreviation) VALUES('Gambia', 'GMB');
INSERT INTO countries (name,abbreviation) VALUES('Georgia', 'GEO');
INSERT INTO countries (name,abbreviation) VALUES('Islas Georgias del Sur y Sandwich del Sur', 'SGS');
INSERT INTO countries (name,abbreviation) VALUES('Ghana', 'GHA');
INSERT INTO countries (name,abbreviation) VALUES('Gibraltar', 'GIB');
INSERT INTO countries (name,abbreviation) VALUES('Granada', 'GRD');
INSERT INTO countries (name,abbreviation) VALUES('Grecia', 'GRC');
INSERT INTO countries (name,abbreviation) VALUES('Groenlandia', 'GRL');
INSERT INTO countries (name,abbreviation) VALUES('Guadalupe', 'GLP');
INSERT INTO countries (name,abbreviation) VALUES('Guam', 'GUM');
INSERT INTO countries (name,abbreviation) VALUES('Guatemala', 'GTM');
INSERT INTO countries (name,abbreviation) VALUES('Guayana Francesa', 'GUF');
INSERT INTO countries (name,abbreviation) VALUES('Guernsey', 'GGY');
INSERT INTO countries (name,abbreviation) VALUES('Guinea', 'GIN');
INSERT INTO countries (name,abbreviation) VALUES('Guinea Ecuatorial', 'GNQ');
INSERT INTO countries (name,abbreviation) VALUES('Guinea-Bissau', 'GNB');
INSERT INTO countries (name,abbreviation) VALUES('Guyana', 'GUY');
INSERT INTO countries (name,abbreviation) VALUES('Haití', 'HTI');
INSERT INTO countries (name,abbreviation) VALUES('Islas Heard y McDonald', 'HMD');
INSERT INTO countries (name,abbreviation) VALUES('Honduras', 'HND');
INSERT INTO countries (name,abbreviation) VALUES('Hong Kong', 'HKG');
INSERT INTO countries (name,abbreviation) VALUES('Hungría', 'HUN');
INSERT INTO countries (name,abbreviation) VALUES('India', 'IND');
INSERT INTO countries (name,abbreviation) VALUES('Indonesia', 'IDN');
INSERT INTO countries (name,abbreviation) VALUES('Irán', 'IRN');
INSERT INTO countries (name,abbreviation) VALUES('Iraq', 'IRQ');
INSERT INTO countries (name,abbreviation) VALUES('Irlanda', 'IRL');
INSERT INTO countries (name,abbreviation) VALUES('Islandia', 'ISL');
INSERT INTO countries (name,abbreviation) VALUES('Israel', 'ISR');
INSERT INTO countries (name,abbreviation) VALUES('Italia', 'ITA');
INSERT INTO countries (name,abbreviation) VALUES('Jamaica', 'JAM');
INSERT INTO countries (name,abbreviation) VALUES('Japón', 'JPN');
INSERT INTO countries (name,abbreviation) VALUES('Jersey', 'JEY');
INSERT INTO countries (name,abbreviation) VALUES('Jordania', 'JOR');
INSERT INTO countries (name,abbreviation) VALUES('Kazajistán', 'KAZ');
INSERT INTO countries (name,abbreviation) VALUES('Kenia', 'KEN');
INSERT INTO countries (name,abbreviation) VALUES('Kirguistán', 'KGZ');
INSERT INTO countries (name,abbreviation) VALUES('Kiribati', 'KIR');
INSERT INTO countries (name,abbreviation) VALUES('Kuwait', 'KWT');
INSERT INTO countries (name,abbreviation) VALUES('Laos', 'LAO');
INSERT INTO countries (name,abbreviation) VALUES('Lesoto', 'LSO');
INSERT INTO countries (name,abbreviation) VALUES('Letonia', 'LVA');
INSERT INTO countries (name,abbreviation) VALUES('Líbano', 'LBN');
INSERT INTO countries (name,abbreviation) VALUES('Liberia', 'LBR');
INSERT INTO countries (name,abbreviation) VALUES('Libia', 'LBY');
INSERT INTO countries (name,abbreviation) VALUES('Liechtenstein', 'LIE');
INSERT INTO countries (name,abbreviation) VALUES('Lituania', 'LTU');
INSERT INTO countries (name,abbreviation) VALUES('Luxemburgo', 'LUX');
INSERT INTO countries (name,abbreviation) VALUES('Macao', 'MAC');
INSERT INTO countries (name,abbreviation) VALUES('ARY Macedonia', 'MKD');
INSERT INTO countries (name,abbreviation) VALUES('Madagascar', 'MDG');
INSERT INTO countries (name,abbreviation) VALUES('Malasia', 'MYS');
INSERT INTO countries (name,abbreviation) VALUES('Malawi', 'MWI');
INSERT INTO countries (name,abbreviation) VALUES('Maldivas', 'MDV');
INSERT INTO countries (name,abbreviation) VALUES('Malí', 'MLI');
INSERT INTO countries (name,abbreviation) VALUES('Malta', 'MLT');
INSERT INTO countries (name,abbreviation) VALUES('Islas Malvinas', 'FLK');
INSERT INTO countries (name,abbreviation) VALUES('Isla de Man', 'IMN');
INSERT INTO countries (name,abbreviation) VALUES('Islas Marianas del Norte', 'MNP');
INSERT INTO countries (name,abbreviation) VALUES('Marruecos', 'MAR');
INSERT INTO countries (name,abbreviation) VALUES('Islas Marshall', 'MHL');
INSERT INTO countries (name,abbreviation) VALUES('Martinica', 'MTQ');
INSERT INTO countries (name,abbreviation) VALUES('Mauricio', 'MUS');
INSERT INTO countries (name,abbreviation) VALUES('Mauritania', 'MRT');
INSERT INTO countries (name,abbreviation) VALUES('Mayotte', 'MYT');
INSERT INTO countries (name,abbreviation) VALUES('México', 'MEX');
INSERT INTO countries (name,abbreviation) VALUES('Micronesia', 'FSM');
INSERT INTO countries (name,abbreviation) VALUES('Moldavia', 'MDA');
INSERT INTO countries (name,abbreviation) VALUES('Mónaco', 'MCO');
INSERT INTO countries (name,abbreviation) VALUES('Mongolia', 'MNG');
INSERT INTO countries (name,abbreviation) VALUES('Montenegro', 'MNE');
INSERT INTO countries (name,abbreviation) VALUES('Montserrat', 'MSR');
INSERT INTO countries (name,abbreviation) VALUES('Mozambique', 'MOZ');
INSERT INTO countries (name,abbreviation) VALUES('Myanmar', 'MMR');
INSERT INTO countries (name,abbreviation) VALUES('Namibia', 'NAM');
INSERT INTO countries (name,abbreviation) VALUES('Nauru', 'NRU');
INSERT INTO countries (name,abbreviation) VALUES('Isla de Navidad', 'CXR');
INSERT INTO countries (name,abbreviation) VALUES('Nepal', 'NPL');
INSERT INTO countries (name,abbreviation) VALUES('Nicaragua', 'NIC');
INSERT INTO countries (name,abbreviation) VALUES('Níger', 'NER');
INSERT INTO countries (name,abbreviation) VALUES('Nigeria', 'NGA');
INSERT INTO countries (name,abbreviation) VALUES('Niue', 'NIU');
INSERT INTO countries (name,abbreviation) VALUES('Norfolk', 'NFK');
INSERT INTO countries (name,abbreviation) VALUES('Noruega', 'NOR');
INSERT INTO countries (name,abbreviation) VALUES('Nueva Caledonia', 'NCL');
INSERT INTO countries (name,abbreviation) VALUES('Nueva Zelanda', 'NZL');
INSERT INTO countries (name,abbreviation) VALUES('Omán', 'OMN');
INSERT INTO countries (name,abbreviation) VALUES('Países Bajos', 'NLD');
INSERT INTO countries (name,abbreviation) VALUES('Pakistán', 'PAK');
INSERT INTO countries (name,abbreviation) VALUES('Palaos', 'PLW');
INSERT INTO countries (name,abbreviation) VALUES('Palestina(ANP)', 'PSE');
INSERT INTO countries (name,abbreviation) VALUES('Panamá', 'PAN');
INSERT INTO countries (name,abbreviation) VALUES('Papúa Nueva Guinea', 'PNG');
INSERT INTO countries (name,abbreviation) VALUES('Paraguay', 'PRY');
INSERT INTO countries (name,abbreviation) VALUES('Perú', 'PER');
INSERT INTO countries (name,abbreviation) VALUES('Islas Pitcairn', 'PCN');
INSERT INTO countries (name,abbreviation) VALUES('Polinesia Francesa', 'PYF');
INSERT INTO countries (name,abbreviation) VALUES('Polonia', 'POL');
INSERT INTO countries (name,abbreviation) VALUES('Portugal', 'PRT');
INSERT INTO countries (name,abbreviation) VALUES('Puerto Rico', 'PRI');
INSERT INTO countries (name,abbreviation) VALUES('Qatar', 'QAT');
INSERT INTO countries (name,abbreviation) VALUES('Reino Unido', 'GBR');
INSERT INTO countries (name,abbreviation) VALUES('Reunión', 'REU');
INSERT INTO countries (name,abbreviation) VALUES('Ruanda', 'RWA');
INSERT INTO countries (name,abbreviation) VALUES('Rumania', 'ROU');
INSERT INTO countries (name,abbreviation) VALUES('Rusia', 'RUS');
INSERT INTO countries (name,abbreviation) VALUES('Sahara Occidental', 'ESH');
INSERT INTO countries (name,abbreviation) VALUES('Islas Salomón', 'SLB');
INSERT INTO countries (name,abbreviation) VALUES('Samoa', 'WSM');
INSERT INTO countries (name,abbreviation) VALUES('Samoa Americana', 'ASM');
INSERT INTO countries (name,abbreviation) VALUES('San Cristóbal y Nieves', 'KNA');
INSERT INTO countries (name,abbreviation) VALUES('San Marino', 'SMR');
INSERT INTO countries (name,abbreviation) VALUES('San Pedro y Miquelón', 'SPM');
INSERT INTO countries (name,abbreviation) VALUES('San Vicente y las Granadinas', 'VCT');
INSERT INTO countries (name,abbreviation) VALUES('Santa Helena', 'SHN');
INSERT INTO countries (name,abbreviation) VALUES('Santa Lucía', 'LCA');
INSERT INTO countries (name,abbreviation) VALUES('Santo Tomé y Príncipe', 'STP');
INSERT INTO countries (name,abbreviation) VALUES('Senegal', 'SEN');
INSERT INTO countries (name,abbreviation) VALUES('Serbia', 'SRB');
INSERT INTO countries (name,abbreviation) VALUES('Seychelles', 'SYC');
INSERT INTO countries (name,abbreviation) VALUES('Sierra Leona', 'SLE');
INSERT INTO countries (name,abbreviation) VALUES('Singapur', 'SGP');
INSERT INTO countries (name,abbreviation) VALUES('Siria', 'SYR');
INSERT INTO countries (name,abbreviation) VALUES('Somalia', 'SOM');
INSERT INTO countries (name,abbreviation) VALUES('Sri Lanka', 'LKA');
INSERT INTO countries (name,abbreviation) VALUES('Suazilandia', 'SWZ');
INSERT INTO countries (name,abbreviation) VALUES('Sudáfrica', 'ZAF');
INSERT INTO countries (name,abbreviation) VALUES('Sudán', 'SDN');
INSERT INTO countries (name,abbreviation) VALUES('Suecia', 'SWE');
INSERT INTO countries (name,abbreviation) VALUES('Suiza', 'CHE');
INSERT INTO countries (name,abbreviation) VALUES('Surinam', 'SUR');
INSERT INTO countries (name,abbreviation) VALUES('Svalbard y Jan Mayen', 'SJM');
INSERT INTO countries (name,abbreviation) VALUES('Tailandia', 'THA');
INSERT INTO countries (name,abbreviation) VALUES('Taiwán', 'TWN');
INSERT INTO countries (name,abbreviation) VALUES('Tanzania', 'TZA');
INSERT INTO countries (name,abbreviation) VALUES('Tayikistán', 'TJK');
INSERT INTO countries (name,abbreviation) VALUES('Territorio Británico del Océano Índico', 'IOT');
INSERT INTO countries (name,abbreviation) VALUES('Territorios Australes Franceses', 'ATF');
INSERT INTO countries (name,abbreviation) VALUES('Timor Oriental', 'TLS');
INSERT INTO countries (name,abbreviation) VALUES('Togo', 'TGO');
INSERT INTO countries (name,abbreviation) VALUES('Tokelau', 'TKL');
INSERT INTO countries (name,abbreviation) VALUES('Tonga', 'TON');
INSERT INTO countries (name,abbreviation) VALUES('Trinidad y Tobago', 'TTO');
INSERT INTO countries (name,abbreviation) VALUES('Túnez', 'TUN');
INSERT INTO countries (name,abbreviation) VALUES('Islas Turcas y Caicos', 'TCA');
INSERT INTO countries (name,abbreviation) VALUES('Turkmenistán', 'TKM');
INSERT INTO countries (name,abbreviation) VALUES('Turquía', 'TUR');
INSERT INTO countries (name,abbreviation) VALUES('Tuvalu', 'TUV');
INSERT INTO countries (name,abbreviation) VALUES('Ucrania', 'UKR');
INSERT INTO countries (name,abbreviation) VALUES('Uganda', 'UGA');
INSERT INTO countries (name,abbreviation) VALUES('Uruguay', 'URY');
INSERT INTO countries (name,abbreviation) VALUES('Uzbekistán', 'UZB');
INSERT INTO countries (name,abbreviation) VALUES('Vanuatu', 'VUT');
INSERT INTO countries (name,abbreviation) VALUES('Ciudad del Vaticano', 'VAT');
INSERT INTO countries (name,abbreviation) VALUES('Venezuela', 'VEN');
INSERT INTO countries (name,abbreviation) VALUES('Vietnam', 'VNM');
INSERT INTO countries (name,abbreviation) VALUES('Islas Vírgenes Británicas', 'VGB');
INSERT INTO countries (name,abbreviation) VALUES('Islas Vírgenes Estadounidenses', 'VIR');
INSERT INTO countries (name,abbreviation) VALUES('Wallis y Futuna', 'WLF');
INSERT INTO countries (name,abbreviation) VALUES('Yemen', 'YEM');
INSERT INTO countries (name,abbreviation) VALUES('Yibuti', 'DJI');
INSERT INTO countries (name,abbreviation) VALUES('Zambia', 'ZMB');
INSERT INTO countries (name,abbreviation) VALUES('Zimbabue', 'ZWE');