use threeplusone;

# Test
# McGrady

# Season
Delete from seasons where id = 1;
INSERT INTO seasons (year, creation_date) VALUES ('2017', 0);

# Teams
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Atlanta Hawks','ATL',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Charlotte Hornets','CHA',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Miami Heat','MIA',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Orlando Magic','ORL',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Washington Wizards','WAS',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Boston Celtics', 'BOS',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Brooklyn Nets', 'BKN',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('New York Knicks', 'NYK',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Philadelphia 76ers','PHI',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Toronto Raptors','TOR',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Chicago Bulls','CHI',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Cleveland Cavaliers','CLE',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Detroit Pistons','DET',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Indiana Pacers','IND',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Milwaukee Bucks','MIL',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Denver Nuggets','DEN',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Minnesota TimberWolves','MIN',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Oklahoma City Thunder','OKC',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Portland Trail Blazers','POR',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Utah Jazz','UTA',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Golden State Warriors','GSW',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Los Ángeles Clippers','LAC',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Los Ángeles Lakers','LAL',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Phoenix Suns','PHO',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Sacramento Kings','SAC',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Dallas Mavericks','DAL',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Houston Rockets','HOU',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('Memphis Grizzlies','MEM',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('New Orleans Pelicans','NOP',(SELECT id FROM countries where name like ('Estados Unidos')),0);
INSERT INTO teams (name, abbreviation, id_country, creation_date) VALUES ('San Antonio Spurs','SAS',(SELECT id FROM countries where name like ('Estados Unidos')),0);

# Players
INSERT INTO players(first_name, last_name, nick_name, creation_date) VALUES('Elfrid','Payton','',0);
INSERT INTO players(first_name, last_name, nick_name, creation_date) VALUES('Aaron','Gordon','',0);
INSERT INTO players(first_name, last_name, nick_name, creation_date) VALUES('Evan','Fournier','Don´t Google my name',0);
INSERT INTO players(first_name, last_name, nick_name, creation_date) VALUES('Terrence','Ross','T-Ross',0);
INSERT INTO players(first_name, last_name, nick_name, creation_date) VALUES('Nikola','Vucevich','Vooch',0);
INSERT INTO players(first_name, last_name, nick_name, creation_date) VALUES('De´Angelo','Russel','Ice on my Veins',0);
INSERT INTO players(first_name, last_name, nick_name, creation_date) VALUES('Isaiah','Thomas','Mr 4º Quarter',0);

# Competitions
INSERT INTO competitions (id_season,name,abbreviation,division,id_country,type,init_date,end_date,creation_date)
VALUES ((SELECT id from seasons as s where s.year like '2017'),'National Basketball Asociation','NBA','1',(SELECT id FROM countries where name like ('Estados Unidos')),'Liga',1472680800000,1472680800000,0);


# Groups
INSERT INTO groups (id_competition,name,creation_date) VALUES ((SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),'West',0);
INSERT INTO groups (id_competition,name,creation_date) VALUES ((SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),'East',0);

# SubGroups
INSERT INTO subgroups (id_group,name,creation_date) VALUES ((SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),'NorthWest',0);
INSERT INTO subgroups (id_group,name,creation_date) VALUES ((SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),'SouthWest',0);
INSERT INTO subgroups (id_group,name,creation_date) VALUES ((SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),'Pacific',0);
INSERT INTO subgroups (id_group,name,creation_date) VALUES ((SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),'Atlantic',0);
INSERT INTO subgroups (id_group,name,creation_date) VALUES ((SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),'SouthEast',0);
INSERT INTO subgroups (id_group,name,creation_date) VALUES ((SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),'Central',0);
# Inscriptions
# NBA 2
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Atlanta Hawks'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'SouthEast' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Brooklyn Nets'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Atlantic' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,id_arena,creation_date) VALUES ((SELECT id FROM teams where name like 'Boston Celtics'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Atlantic' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),(SELECT id from arenas where name like 'TD Garden'),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Charlotte Hornets'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'SouthEast' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Chicago Bulls'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Central' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Cleveland Cavaliers'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Central' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Dallas Mavericks'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'SouthWest' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Denver Nuggets'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'NorthWest' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Detroit Pistons'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Central' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,id_arena,creation_date) VALUES ((SELECT id FROM teams where name like 'Golden State Warriors'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Pacific' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),(SELECT id from arenas where name like 'Oracle Arena'),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Houston Rockets'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'SouthWest' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Indiana Pacers'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Central' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,id_arena,creation_date) VALUES ((SELECT id FROM teams where name like 'Los Ángeles Clippers'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Pacific' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),(SELECT id from arenas where name like 'Staples Center'),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,id_arena,creation_date) VALUES ((SELECT id FROM teams where name like 'Los Ángeles Lakers'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Pacific' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),(SELECT id from arenas where name like 'Staples Center'),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Memphis Grizzlies'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'SouthWest' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Miami Heat'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'SouthEast' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Milwaukee Bucks'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Central' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Minnesota TimberWolves'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'NorthWest' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'New Orleans Pelicans'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'SouthWest' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,id_arena,creation_date) VALUES ((SELECT id FROM teams where name like 'New York Knicks'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Atlantic' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),(SELECT id from arenas where name like 'Madison Square Garden'),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Oklahoma City Thunder'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'NorthWest' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,id_arena,creation_date) VALUES ((SELECT id FROM teams where name like 'Orlando Magic'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'SouthEast' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),(SELECT id from arenas where name like 'Amway Arena'),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Philadelphia 76ers'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Atlantic' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Phoenix Suns'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Pacific' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Portland Trail Blazers'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'NorthWest' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Sacramento Kings'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Pacific' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'San Antonio Spurs'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'SouthWest' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Toronto Raptors'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'Atlantic' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Utah Jazz'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'NorthWest' and id_group in (SELECT id from groups where name like 'West' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);
INSERT INTO inscriptions (id_team,id_competition,id_group,id_subgroup,creation_date) VALUES ((SELECT id FROM teams where name like 'Washington Wizards'),(SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')),(SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017'))),(SELECT id FROM subgroups where name like 'SouthEast' and id_group in (SELECT id from groups where name like 'East' and id_competition in (SELECT id FROM competitions where abbreviation like 'NBA' and id_season in (SELECT id from seasons as s where s.year like '2017')))),0);


#Contracts
